"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Globe } from "lucide-react"

interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

const translations: Translations = {
  es: {
    // Navigation
    services: "Servicios",
    chatbots: "Chatbots",
    cases: "Casos de Uso",
    contact: "Contacto",
    scheduleDemo: "Agenda Demo",
    home: "Inicio",

    // Hero
    heroTitle1: "ZERO",
    heroTitle2: "LIMITS",
    heroSubtitle: "Automatiza y potencia tu negocio con IA, sin límites.",
    heroDescription:
      "Transformamos tus ventas, soporte y operaciones con soluciones de inteligencia artificial personalizadas que impulsan el crecimiento exponencial de tu empresa.",
    scheduleDemoBtn: "Agenda una Demo",
    viewServices: "Ver Servicios",

    // Benefits
    freeDemo: "Demo gratuita en 15 minutos",
    implementation: "Implementación en 48 horas",
    support: "Soporte 24/7",
    whatsappDirect: "WhatsApp Directo",

    // Sections
    whyChoose: "¿Por qué elegir Æternity?",
    revolutionaryBenefits: "Beneficios Revolucionarios",
    transformBenefits: "Descubre los beneficios que transformarán tu negocio para siempre",
    extremeSpeed: "Velocidad Extrema",
    totalEfficiency: "Eficiencia Total",
    service247: "Servicio 24/7",
    guaranteedROI: "ROI Garantizado",
    premiumExperience: "Experiencia Premium",
    advancedSecurity: "Seguridad Avanzada",

    // Descriptions
    extremeSpeedDesc: "Automatiza tareas repetitivas para acelerar tus operaciones hasta 10x más rápido",
    totalEfficiencyDesc: "Optimiza procesos y elimina errores humanos con sistemas inteligentes y precisos",
    service247Desc: "Atiende a tus clientes las 24 horas con asistentes virtuales que nunca descansan",
    guaranteedROIDesc: "Reduce gastos operativos hasta 70% mientras aumentas la productividad exponencialmente",
    premiumExperienceDesc: "Mejora la satisfacción del cliente con respuestas inmediatas y atención personalizada",
    advancedSecurityDesc: "Protección de datos de nivel empresarial con encriptación y cumplimiento normativo",

    // CTA
    readyToEliminate: "¿Listo para eliminar los límites de tu negocio?",
    joinCompanies:
      "Únete a las empresas que ya están transformando sus resultados con Æternity. Agenda una demo personalizada y descubre el potencial infinito de tu negocio.",
    scheduleDemoFree: "Agenda Demo GRATIS",
    viewChatbots: "Ver Chatbots",
    liveChat: "Chat en vivo ahora",
    viewDemoLive: "Ver Demo en Vivo",

    // Footer
    footerDescription:
      "Transformación digital sin límites. Automatización e IA para impulsar tu negocio hacia el futuro.",
    pages: "Páginas",
    servicesFooter: "Servicios",
    contactFooter: "Contacto",
    salesAutomation: "Automatización de Ventas",
    intelligentSupport: "Soporte Inteligente",
    automatedOperations: "Operaciones Automatizadas",
    rightsReserved: "Todos los derechos reservados.",
    tagline: "Zero Limits, Infinite Possibilities.",

    // Testimonials
    realTestimonials: "Testimonios Reales",
    whatClientsSay: "Lo Que Dicen Nuestros Clientes",
    realStories: "Historias reales de empresas que han transformado su negocio con Æternity",
    testimonial1:
      "Gracias a Æternity, nuestro tiempo de respuesta bajó de horas a minutos, y la satisfacción del cliente está por las nubes. ¡Increíble!",
    testimonial2:
      "Los asistentes virtuales de Æternity nos ayudaron a aumentar un 45% las ventas online en solo 3 meses. ROI espectacular.",
    testimonial3:
      "La automatización de procesos nos permitió enfocar al equipo en tareas estratégicas. El ROI fue inmediato y sostenible.",
    author1: "Juan Pérez",
    author2: "María López",
    author3: "Carlos Mendoza",
    position1: "Director de Operaciones",
    position2: "CEO",
    position3: "Gerente General",
    company1: "SolTech",
    company2: "LegalTrust",
    company3: "HealthPlus",

    // Results
    provenResults: "Resultados Comprobados",
    impactNumbers: "Números Que Impactan",
    extraordinaryTransformations:
      "Nuestros clientes han logrado transformaciones extraordinarias y resultados medibles",
    conversionRate: "Tasa de Conversión",
    roiDays: "ROI en 60 días",
    responseTime: "Menos tiempo de respuesta",
    clientSatisfaction: "Satisfacción de clientes",
    wantResults: "Quiero Estos Resultados",

    // FAQ Section
    frequentQuestions: "Preguntas Frecuentes",
    faqTitle: "Todo lo que Necesitas Saber",
    faqSubtitle: "Respuestas honestas a las preguntas más importantes sobre chatbots e IA para tu negocio",
    faqGeneral: "General",
    faqImplementation: "Implementación",
    faqCosts: "Costos",
    faqFunctionalities: "Funcionalidades",
    faqResults: "Resultados",
    faqSupport: "Soporte",
    faqNotFound: "¿No encontraste tu respuesta?",
    faqContactTeam: "Nuestro equipo está disponible 24/7 para resolver cualquier duda específica sobre tu proyecto",
    faqWhatsApp: "Pregunta por WhatsApp",
    faqScheduleDemo: "Agenda Demo Gratis",

    // Contact Page
    letsSpeak: "Hablemos",
    contactTitle: "Contacta con Nosotros",
    contactSubtitle:
      "¿Listo para transformar tu negocio? Estamos aquí para ayudarte a dar el siguiente paso hacia la automatización inteligente.",
    sendMessage: "Envíanos un Mensaje",
    fullName: "Nombre Completo",
    company: "Empresa",
    email: "Email",
    phone: "Teléfono",
    message: "Mensaje",
    sendButton: "Enviar Mensaje",
    sending: "Enviando...",
    contactInfo: "Información de Contacto",
    schedule: "Horario",
    alwaysAvailable: "24/7 - Siempre disponibles",
    followSocial: "Síguenos en Redes",
    needHelp: "¿Necesitas ayuda inmediata?",
    teamAvailable: "Nuestro equipo está disponible 24/7 para resolver tus dudas",
    chatNow: "Chat Ahora",
    directEmail: "Email Directo",
    messageSent: "¡Mensaje Enviado Exitosamente!",
    thankYou:
      "Gracias por contactarnos. Hemos recibido tu mensaje y nuestro equipo se pondrá en contacto contigo en las próximas 24 horas.",
    responseIn24: "Respuesta en 24 horas",
    sentTo: "Enviado a",
    backHome: "Volver al Inicio",
    yourCompleteName: "Tu nombre completo",
    companyName: "Nombre de tu empresa",
    yourEmail: "tu@email.com",
    phoneNumber: "+1 (555) 123-4567",
    tellUsAbout: "Cuéntanos sobre tu proyecto y cómo podemos ayudarte...",
    invalidEmail: "*Este correo no es válido",

    // Services Page
    intelligentSolutions: "Soluciones Inteligentes",
    servicesTitle: "Nuestros Servicios",
    servicesSubtitle: "Transformamos cada área de tu negocio con IA especializada y personalizada",
    intelligentSales: "Ventas Inteligentes",
    revolutionarySupport: "Soporte Revolucionario",
    automatedOperations: "Operaciones Automatizadas",
    advancedFeatures: "Características Avanzadas",
    instantResponse: "Respuesta Instantánea",
    enterpriseSecurity: "Seguridad Empresarial",
    advancedAnalytics: "Analytics Avanzados",
    scalability: "Escalabilidad",
    readyTransform: "¿Listo para transformar tu negocio?",
    schedulePersonalized:
      "Agenda una demo personalizada y descubre cómo nuestros servicios pueden revolucionar tu empresa",
    requestDemo: "Solicitar Demo",
    whatsappConsult: "Consulta WhatsApp",
    moreInformation: "Más Información",
    instantResponseDesc: "Menos de 2 segundos de tiempo de respuesta",
    enterpriseSecurityDesc: "Encriptación de nivel bancario",
    advancedAnalyticsDesc: "Métricas detalladas y reportes en tiempo real",
    scalabilityDesc: "Crece con tu negocio sin límites",
    cuttingEdgeTech: "Tecnología de vanguardia para resultados excepcionales",

    // Chatbots Page
    intelligentChatbots: "Chatbots Inteligentes",
    chatbotsTitle: "Chatbots Para Cada Plataforma",
    chatbotsSubtitle:
      "Crea asistentes virtuales personalizados que responden al instante en todas las plataformas donde están tus clientes",
    website: "Sitio Web",
    whatsappBusiness: "WhatsApp Business",
    instagramDMs: "Instagram DMs",
    facebookMessenger: "Facebook Messenger",
    intelligentSMS: "SMS Inteligente",
    emailMarketing: "Email Marketing",
    webDemo: "Ver Demo Web",
    whatsappDemo: "Demo WhatsApp",
    instagramDemo: "Demo Instagram",
    facebookDemo: "Demo Facebook",
    smsDemo: "Demo SMS",
    emailDemo: "Demo Email",
    completeAnalytics: "Analytics Completos",
    readyTransformChatbot: "¿Listo para transformar tu negocio con un chatbot?",
    contactToday:
      "¡Contáctanos hoy mismo y descubre cómo un chatbot personalizado puede revolucionar tu interacción con los clientes!",
    contactEmail: "Contáctanos por correo",
    createMyChatbot: "Crear mi Chatbot",
    customizableWidget: "Widget personalizable",
    easyIntegration: "Integración fácil",
    multipleLanguages: "Múltiples idiomas",
    officialAPI: "API oficial",
    multimediaMessages: "Mensajes multimedia",
    integratedCatalog: "Catálogo integrado",
    detailedMetrics: "Métricas detalladas",
    interactiveStories: "Stories interactivas",
    automaticResponses: "Respuestas automáticas",
    commentManagement: "Gestión de comentarios",
    leadCapture: "Lead capture",
    integratedMessenger: "Messenger integrado",
    interactiveAds: "Anuncios interactivos",
    automaticSequences: "Secuencias automáticas",
    crmIntegrated: "CRM integrado",
    massiveSMS: "SMS masivos",
    advancedSegmentation: "Segmentación avanzada",
    roiTracking: "ROI tracking",
    aiPersonalization: "Personalización IA",
    abTesting: "A/B testing",
    completeAnalytics2: "Analytics completos",
    webIntegratedChatbot:
      "Chatbot integrado en tu sitio web que convierte visitantes en clientes las 24 horas del día.",
    whatsappAutomation: "Automatiza conversaciones en WhatsApp con respuestas inteligentes y seguimiento de leads.",
    instagramAutomation: "Responde automáticamente a mensajes directos y comentarios en Instagram.",
    facebookAutomation: "Chatbot para Facebook que maneja consultas y genera leads automáticamente.",
    smsAutomation: "Campañas de SMS automatizadas con respuestas inteligentes y seguimiento.",
    emailAutomation: "Automatización de email marketing con respuestas inteligentes y personalización.",
    instantResponseFeature: "Respuesta Instantánea",
    customizable100: "100% Personalizable",
    available247: "Disponible 24/7",
    advancedAI: "IA Avanzada",
    responds2seconds: "Responde en menos de 2 segundos, 24/7 sin interrupciones",
    adaptTone: "Adapta el tono, personalidad y respuestas a tu marca",
    learnsConversations: "Aprende de cada conversación para mejorar continuamente",
    detailedMetricsOptimize: "Métricas detalladas para optimizar conversiones",

    // Cases Page
    successCases: "Casos de Éxito",
    casesTitle: "Industrias Transformadas",
    casesSubtitle: "Soluciones adaptadas a las necesidades específicas de cada sector",
    solarEnergy: "🌞 Energía Solar",
    legalSector: "⚖️ Sector Legal",
    healthSector: "🏥 Salud",
    ecommerce: "🛒 E-commerce",
    renewableEnergy: "Energía Renovable",
    legalServices: "Servicios Legales",
    healthSector2: "Sector Salud",
    electronicCommerce: "Comercio Electrónico",
    mainFeatures: "Características Principales:",
    obtainedResults: "Resultados Obtenidos:",
    viewCompleteCase: "Ver Caso Completo",
    transversalBenefits: "Beneficios Transversales",
    benefitsDescription: "Independientemente de tu industria, estos son los beneficios que obtienes",
    salesIncrease: "Aumento de Ventas",
    timeSaving: "Ahorro de Tiempo",
    betterExperience: "Mejor Experiencia",
    provenROI: "ROI Comprobado",
    industryNotHere: "¿Tu industria no está aquí?",
    dontWorry:
      "No te preocupes. Creamos soluciones personalizadas para cualquier sector. Cuéntanos tu caso específico.",
    consultCase: "Consultar Mi Caso",
    solarEnergyDesc: "Asistentes virtuales que educan sobre instalaciones solares y calculan ahorros en tiempo real.",
    legalSectorDesc: "Chatbots legales que responden consultas básicas y recopilan información para casos.",
    healthSectorDesc: "Agentes virtuales para triage de pacientes y gestión inteligente de citas médicas.",
    ecommerceDesc: "Recomendadores inteligentes que ofrecen asistencia personalizada y aumentan ventas.",
    automaticCalculator: "Calculadora de ahorros automática",
    solarEducation: "Educación sobre paneles solares",
    qualifiedLeadsTracking: "Seguimiento de leads calificados",
    quotationIntegration: "Integración con sistemas de cotización",
    qualifiedLeads: "Leads calificados",
    moreConversions: "Más conversiones",
    availableAttention: "Atención disponible",
    basicLegalConsultations: "Consultas legales básicas automatizadas",
    caseInfoCollection: "Recopilación de información de casos",
    lawyerAppointments: "Programación de citas con abogados",
    legalKnowledgeBase: "Base de conocimiento legal actualizada",
    consultationsAttended: "Consultas atendidas",
    lessAdminTime: "Menos tiempo admin",
    clientSatisfaction2: "Satisfacción cliente",
    automaticTriage: "Triage automático de pacientes",
    intelligentScheduling: "Programación inteligente de citas",
    automaticReminders: "Recordatorios automáticos",
    basicHistoryManagement: "Gestión de historiales básicos",
    operationalEfficiency: "Eficiencia operativa",
    fewerMissedCalls: "Menos llamadas perdidas",
    appointmentPunctuality: "Puntualidad en citas",
    personalizedRecommendations: "Recomendaciones personalizadas",
    shoppingAssistance247: "Asistencia de compra 24/7",
    abandonedCartTracking: "Seguimiento de carritos abandonados",
    automatedPostSale: "Soporte post-venta automatizado",
    averageOrderValue: "Valor promedio pedido",
    fewerAbandonedCarts: "Menos carritos abandonados",
    resolvedConsultations: "Consultas resueltas",
    salesIncreaseAvg: "Incremento promedio del 40% en conversiones",
    timeSavingReduction: "Reducción del 70% en tiempo de respuesta",
    betterExperiencePercent: "95% de satisfacción del cliente",
    provenROIReturn: "Retorno de inversión en menos de 60 días",

    // Demo Page
    demoTitle: "Cuéntanos sobre tu Negocio",
    demoSubtitle: "Con esta información crearemos una demo personalizada específicamente para tus necesidades",
    personalizedDemo: "Demo Personalizada",
    contactInfoStep: "Información de Contacto",
    businessInfoStep: "Sobre tu Negocio",
    botConfigurationStep: "Configuración del Bot",
    finalPersonalizationStep: "Personalización Final",
    previous: "Anterior",
    next: "Siguiente",
    createDemo: "Crear Mi Demo",
    helpWhatsApp: "Ayuda por WhatsApp",
    demoReady: "¡Perfecto! Tu Demo Está en Camino",
    demoArriving: "Tu demo llegará en menos de 24 horas",
    demoDescription:
      "Hemos recibido toda tu información y nuestro equipo ya está trabajando en crear una demo personalizada específicamente para tu negocio.",
    sendPersonalizedDemo: "Para enviarte tu demo personalizada",
    personalizeYourSolution: "Para personalizar tu solución",
    personalizeVirtualAssistant: "Personalicemos tu asistente virtual",
    finalDetailsDemo: "Los últimos detalles para tu demo perfecta",
    fullNameRequired: "Nombre Completo *",
    businessEmail: "Email Empresarial *",
    phoneWhatsApp: "Teléfono/WhatsApp *",
    companyRequired: "Empresa *",
    yourPosition: "Tu Cargo *",
    haveWebsite: "¿Tienes sitio web? *",
    selectOption: "Selecciona una opción",
    yesHaveWebsite: "Sí, tengo sitio web",
    noWebsite: "No tengo sitio web",
    websiteURL: "URL de tu Sitio Web *",
    helpsUnderstand: "Nos ayuda a entender mejor tu negocio y personalizar la demo",
    perfectAlso:
      "¡Perfecto! También podemos ayudarte a crear un sitio web con chatbot integrado. Lo incluiremos en tu demo personalizada.",
    industrySector: "Industria/Sector *",
    selectIndustry: "Selecciona tu industria",
    companySize: "Tamaño de la Empresa *",
    selectSize: "Selecciona el tamaño",
    justMe: "Solo yo",
    employees2to10: "2-10 empleados",
    employees11to50: "11-50 empleados",
    employees51to200: "51-200 empleados",
    employees200plus: "200+ empleados",
    mainObjectiveBot: "¿Cuál es tu objetivo principal con el bot? *",
    selectObjective: "Selecciona tu objetivo",
    generateMoreLeads: "Generar más leads/ventas",
    improveCustomerService: "Mejorar atención al cliente",
    automateProcesses: "Automatizar procesos",
    reduceOperationalCosts: "Reducir costos de personal",
    attend247: "Atender 24/7",
    qualifyLeadsAutomatically: "Calificar leads automáticamente",
    consultationsPerDay: "¿Cuántas consultas recibes aproximadamente por día? *",
    selectVolume: "Selecciona el volumen",
    consultations1to10: "1-10 consultas",
    consultations11to50: "11-50 consultas",
    consultations51to100: "51-100 consultas",
    consultations100plus: "100+ consultas",
    notSure: "No estoy seguro",
    whatTypeBot: "¿Qué tipo de bot necesitas? *",
    salesBot: "Bot de Ventas",
    supportBot: "Bot de Soporte",
    mixedBot: "Mixto",
    customBot: "Personalizado",
    generateLeadsClose: "Genera leads y cierra ventas",
    handleConsultationsProblems: "Atiende consultas y problemas",
    salesSupportCombined: "Ventas + Soporte combinado",
    specificFunctions: "Funciones específicas",
    whatPlatforms: "¿En qué plataformas quieres el bot? * (Puedes seleccionar varias)",
    monthlyBudget: "Presupuesto Mensual Estimado *",
    selectBudget: "Selecciona tu presupuesto",
    budget300to800: "$300 - $800 USD",
    budget800to1500: "$800 - $1,500 USD",
    budget1500to3000: "$1,500 - $3,000 USD",
    budget3000plus: "$3,000+ USD",
    needCustomQuote: "Necesito cotización personalizada",
    howUrgent: "¿Qué tan urgente es implementar esto? *",
    selectUrgency: "Selecciona urgencia",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    in2to3Months: "En 2-3 meses",
    justExploring: "Solo explorando",
    alreadyHaveBot: "¿Ya tienes algún bot o chatbot? *",
    noFirstBot: "No, es mi primer bot",
    yesButNotWorking: "Sí, pero no funciona bien",
    yesButWantBetter: "Sí, pero quiero uno mejor",
    haveSeveral: "Tengo varios",
    botTonePersonality: "Tono/Personalidad del Bot *",
    selectTone: "Selecciona el tono",
    professionalFormal: "Profesional y formal",
    friendlyClose: "Amigable y cercano",
    funCasual: "Divertido y casual",
    expertTechnical: "Experto y técnico",
    customized: "Personalizado",
    biggestProblem: "¿Cuál es tu mayor problema actual con la atención al cliente?",
    problemExample: "Ej: No podemos atender fuera de horario, perdemos muchos leads, respuestas muy lentas...",
    specialFeatures: "Funcionalidades especiales que te interesan (Opcional)",
    crmIntegration: "Integración con CRM",
    automaticPayments: "Pagos automáticos",
    appointmentsReservations: "Citas/Reservas",
    productCatalog: "Catálogo de productos",
    orderTracking: "Seguimiento de pedidos",
    satisfactionSurveys: "Encuestas de satisfacción",
    multipleLanguagesFeature: "Múltiples idiomas",
    advancedAnalyticsFeature: "Analytics avanzados",
    expectedROI: "¿Qué ROI/resultado esperas obtener? *",
    selectExpectation: "Selecciona tu expectativa",
    moreLeadsSales: "Más leads/ventas",
    reducePersonnelCosts: "Reducir costos de personal",
    betterCustomerExperience: "Mejor experiencia del cliente",
    attention247: "Atención 24/7",
    automateProcessesResult: "Automatizar procesos",
    allAbove: "Todo lo anterior",
    doubtsWhileCompleting: "¿Tienes dudas mientras completas el formulario?",
    personalizedDemoReady: "Demo personalizada lista",
    specificConfiguration: "Configuración específica",
    readyToImplement: "Listo para implementar",
    anyQuestionsWhile: "¿Tienes alguna duda mientras tanto?",
  },
  en: {
    // Navigation
    services: "Services",
    chatbots: "Chatbots",
    cases: "Use Cases",
    contact: "Contact",
    scheduleDemo: "Schedule Demo",
    home: "Home",

    // Hero
    heroTitle1: "ZERO",
    heroTitle2: "LIMITS",
    heroSubtitle: "Automate and boost your business with AI, without limits.",
    heroDescription:
      "We transform your sales, support and operations with personalized artificial intelligence solutions that drive exponential growth of your company.",
    scheduleDemoBtn: "Schedule a Demo",
    viewServices: "View Services",

    // Benefits
    freeDemo: "Free demo in 15 minutes",
    implementation: "Implementation in 48 hours",
    support: "24/7 Support",
    whatsappDirect: "Direct WhatsApp",

    // Sections
    whyChoose: "Why choose Æternity?",
    revolutionaryBenefits: "Revolutionary Benefits",
    transformBenefits: "Discover the benefits that will transform your business forever",
    extremeSpeed: "Extreme Speed",
    totalEfficiency: "Total Efficiency",
    service247: "24/7 Service",
    guaranteedROI: "Guaranteed ROI",
    premiumExperience: "Premium Experience",
    advancedSecurity: "Advanced Security",

    // Descriptions
    extremeSpeedDesc: "Automate repetitive tasks to accelerate your operations up to 10x faster",
    totalEfficiencyDesc: "Optimize processes and eliminate human errors with intelligent and precise systems",
    service247Desc: "Serve your customers 24 hours a day with virtual assistants that never rest",
    guaranteedROIDesc: "Reduce operational expenses up to 70% while exponentially increasing productivity",
    premiumExperienceDesc: "Improve customer satisfaction with immediate responses and personalized attention",
    advancedSecurityDesc: "Enterprise-level data protection with encryption and regulatory compliance",

    // CTA
    readyToEliminate: "Ready to eliminate the limits of your business?",
    joinCompanies:
      "Join the companies that are already transforming their results with Æternity. Schedule a personalized demo and discover the infinite potential of your business.",
    scheduleDemoFree: "Schedule FREE Demo",
    viewChatbots: "View Chatbots",
    liveChat: "Live chat now",
    viewDemoLive: "View Live Demo",

    // Footer
    footerDescription:
      "Digital transformation without limits. Automation and AI to boost your business into the future.",
    pages: "Pages",
    servicesFooter: "Services",
    contactFooter: "Contact",
    salesAutomation: "Sales Automation",
    intelligentSupport: "Intelligent Support",
    automatedOperations: "Automated Operations",
    rightsReserved: "All rights reserved.",
    tagline: "Zero Limits, Infinite Possibilities.",

    // Testimonials
    realTestimonials: "Real Testimonials",
    whatClientsSay: "What Our Clients Say",
    realStories: "Real stories from companies that have transformed their business with Æternity",
    testimonial1:
      "Thanks to Æternity, our response time went from hours to minutes, and customer satisfaction is through the roof. Incredible!",
    testimonial2:
      "Æternity's virtual assistants helped us increase online sales by 45% in just 3 months. Spectacular ROI.",
    testimonial3:
      "Process automation allowed us to focus the team on strategic tasks. The ROI was immediate and sustainable.",
    author1: "John Perez",
    author2: "Maria Lopez",
    author3: "Carlos Mendoza",
    position1: "Operations Director",
    position2: "CEO",
    position3: "General Manager",
    company1: "SolTech",
    company2: "LegalTrust",
    company3: "HealthPlus",

    // Results
    provenResults: "Proven Results",
    impactNumbers: "Numbers That Impact",
    extraordinaryTransformations: "Our clients have achieved extraordinary transformations and measurable results",
    conversionRate: "Conversion Rate",
    roiDays: "ROI in 60 days",
    responseTime: "Less response time",
    clientSatisfaction: "Client satisfaction",
    wantResults: "I Want These Results",

    // FAQ Section
    frequentQuestions: "Frequently Asked Questions",
    faqTitle: "Everything You Need to Know",
    faqSubtitle: "Honest answers to the most important questions about chatbots and AI for your business",
    faqGeneral: "General",
    faqImplementation: "Implementation",
    faqCosts: "Costs",
    faqFunctionalities: "Functionalities",
    faqResults: "Results",
    faqSupport: "Support",
    faqNotFound: "Didn't find your answer?",
    faqContactTeam: "Our team is available 24/7 to resolve any specific questions about your project",
    faqWhatsApp: "Ask via WhatsApp",
    faqScheduleDemo: "Schedule Free Demo",

    // Contact Page
    letsSpeak: "Let's Talk",
    contactTitle: "Contact Us",
    contactSubtitle:
      "Ready to transform your business? We're here to help you take the next step towards intelligent automation.",
    sendMessage: "Send us a Message",
    fullName: "Full Name",
    company: "Company",
    email: "Email",
    phone: "Phone",
    message: "Message",
    sendButton: "Send Message",
    sending: "Sending...",
    contactInfo: "Contact Information",
    schedule: "Schedule",
    alwaysAvailable: "24/7 - Always available",
    followSocial: "Follow us on Social Media",
    needHelp: "Need immediate help?",
    teamAvailable: "Our team is available 24/7 to resolve your questions",
    chatNow: "Chat Now",
    directEmail: "Direct Email",
    messageSent: "Message Sent Successfully!",
    thankYou:
      "Thank you for contacting us. We have received your message and our team will contact you within the next 24 hours.",
    responseIn24: "Response in 24 hours",
    sentTo: "Sent to",
    backHome: "Back to Home",
    yourCompleteName: "Your full name",
    companyName: "Your company name",
    yourEmail: "your@email.com",
    phoneNumber: "+1 (555) 123-4567",
    tellUsAbout: "Tell us about your project and how we can help you...",
    invalidEmail: "*This email is not valid",

    // Services Page
    intelligentSolutions: "Intelligent Solutions",
    servicesTitle: "Our Services",
    servicesSubtitle: "We transform every area of your business with specialized and personalized AI",
    intelligentSales: "Intelligent Sales",
    revolutionarySupport: "Revolutionary Support",
    automatedOperations: "Automated Operations",
    advancedFeatures: "Advanced Features",
    instantResponse: "Instant Response",
    enterpriseSecurity: "Enterprise Security",
    advancedAnalytics: "Advanced Analytics",
    scalability: "Scalability",
    readyTransform: "Ready to transform your business?",
    schedulePersonalized: "Schedule a personalized demo and discover how our services can revolutionize your company",
    requestDemo: "Request Demo",
    whatsappConsult: "WhatsApp Consultation",
    moreInformation: "More Information",
    instantResponseDesc: "Less than 2 seconds response time",
    enterpriseSecurityDesc: "Banking-level encryption",
    advancedAnalyticsDesc: "Detailed metrics and real-time reports",
    scalabilityDesc: "Grows with your business without limits",
    cuttingEdgeTech: "Cutting-edge technology for exceptional results",

    // Chatbots Page
    intelligentChatbots: "Intelligent Chatbots",
    chatbotsTitle: "Chatbots For Every Platform",
    chatbotsSubtitle:
      "Create personalized virtual assistants that respond instantly on all platforms where your customers are",
    website: "Website",
    whatsappBusiness: "WhatsApp Business",
    instagramDMs: "Instagram DMs",
    facebookMessenger: "Facebook Messenger",
    intelligentSMS: "Intelligent SMS",
    emailMarketing: "Email Marketing",
    webDemo: "View Web Demo",
    whatsappDemo: "WhatsApp Demo",
    instagramDemo: "Instagram Demo",
    facebookDemo: "Facebook Demo",
    smsDemo: "SMS Demo",
    emailDemo: "Email Demo",
    completeAnalytics: "Complete Analytics",
    readyTransformChatbot: "Ready to transform your business with a chatbot?",
    contactToday:
      "Contact us today and discover how a personalized chatbot can revolutionize your customer interaction!",
    contactEmail: "Contact us by email",
    createMyChatbot: "Create my Chatbot",
    customizableWidget: "Customizable widget",
    easyIntegration: "Easy integration",
    multipleLanguages: "Multiple languages",
    officialAPI: "Official API",
    multimediaMessages: "Multimedia messages",
    integratedCatalog: "Integrated catalog",
    detailedMetrics: "Detailed metrics",
    interactiveStories: "Interactive stories",
    automaticResponses: "Automatic responses",
    commentManagement: "Comment management",
    leadCapture: "Lead capture",
    integratedMessenger: "Integrated messenger",
    interactiveAds: "Interactive ads",
    automaticSequences: "Automatic sequences",
    crmIntegrated: "CRM integrated",
    massiveSMS: "Massive SMS",
    advancedSegmentation: "Advanced segmentation",
    roiTracking: "ROI tracking",
    aiPersonalization: "AI personalization",
    abTesting: "A/B testing",
    completeAnalytics2: "Complete analytics",
    webIntegratedChatbot: "Chatbot integrated into your website that converts visitors into customers 24 hours a day.",
    whatsappAutomation: "Automate WhatsApp conversations with intelligent responses and lead tracking.",
    instagramAutomation: "Automatically respond to direct messages and comments on Instagram.",
    facebookAutomation: "Facebook chatbot that handles queries and generates leads automatically.",
    smsAutomation: "Automated SMS campaigns with intelligent responses and tracking.",
    emailAutomation: "Email marketing automation with intelligent responses and personalization.",
    instantResponseFeature: "Instant Response",
    customizable100: "100% Customizable",
    available247: "Available 24/7",
    advancedAI: "Advanced AI",
    responds2seconds: "Responds in less than 2 seconds, 24/7 without interruptions",
    adaptTone: "Adapt tone, personality and responses to your brand",
    learnsConversations: "Learns from each conversation to continuously improve",
    detailedMetricsOptimize: "Detailed metrics to optimize conversions",

    // Cases Page
    successCases: "Success Cases",
    casesTitle: "Transformed Industries",
    casesSubtitle: "Solutions adapted to the specific needs of each sector",
    solarEnergy: "🌞 Solar Energy",
    legalSector: "⚖️ Legal Sector",
    healthSector: "🏥 Health",
    ecommerce: "🛒 E-commerce",
    renewableEnergy: "Renewable Energy",
    legalServices: "Legal Services",
    healthSector2: "Health Sector",
    electronicCommerce: "Electronic Commerce",
    mainFeatures: "Main Features:",
    obtainedResults: "Obtained Results:",
    viewCompleteCase: "View Complete Case",
    transversalBenefits: "Transversal Benefits",
    benefitsDescription: "Regardless of your industry, these are the benefits you get",
    salesIncrease: "Sales Increase",
    timeSaving: "Time Saving",
    betterExperience: "Better Experience",
    provenROI: "Proven ROI",
    industryNotHere: "Your industry not here?",
    dontWorry: "Don't worry. We create personalized solutions for any sector. Tell us your specific case.",
    consultCase: "Consult My Case",
    solarEnergyDesc: "Virtual assistants that educate about solar installations and calculate savings in real time.",
    legalSectorDesc: "Legal chatbots that answer basic queries and collect information for cases.",
    healthSectorDesc: "Virtual agents for patient triage and intelligent medical appointment management.",
    ecommerceDesc: "Intelligent recommenders that offer personalized assistance and increase sales.",
    automaticCalculator: "Automatic savings calculator",
    solarEducation: "Solar panel education",
    qualifiedLeadsTracking: "Qualified leads tracking",
    quotationIntegration: "Integration with quotation systems",
    qualifiedLeads: "Qualified leads",
    moreConversions: "More conversions",
    availableAttention: "Available attention",
    basicLegalConsultations: "Automated basic legal consultations",
    caseInfoCollection: "Case information collection",
    lawyerAppointments: "Lawyer appointment scheduling",
    legalKnowledgeBase: "Updated legal knowledge base",
    consultationsAttended: "Consultations attended",
    lessAdminTime: "Less admin time",
    clientSatisfaction2: "Client satisfaction",
    automaticTriage: "Automatic patient triage",
    intelligentScheduling: "Intelligent appointment scheduling",
    automaticReminders: "Automatic reminders",
    basicHistoryManagement: "Basic history management",
    operationalEfficiency: "Operational efficiency",
    fewerMissedCalls: "Fewer missed calls",
    appointmentPunctuality: "Appointment punctuality",
    personalizedRecommendations: "Personalized recommendations",
    shoppingAssistance247: "24/7 shopping assistance",
    abandonedCartTracking: "Abandoned cart tracking",
    automatedPostSale: "Automated post-sale support",
    averageOrderValue: "Average order value",
    fewerAbandonedCarts: "Fewer abandoned carts",
    resolvedConsultations: "Resolved consultations",
    salesIncreaseAvg: "Average 40% increase in conversions",
    timeSavingReduction: "70% reduction in response time",
    betterExperiencePercent: "95% customer satisfaction",
    provenROIReturn: "Return on investment in less than 60 days",

    // Demo Page
    demoTitle: "Tell us about your Business",
    demoSubtitle: "With this information we will create a personalized demo specifically for your needs",
    personalizedDemo: "Personalized Demo",
    contactInfoStep: "Contact Information",
    businessInfoStep: "About your Business",
    botConfigurationStep: "Bot Configuration",
    finalPersonalizationStep: "Final Personalization",
    previous: "Previous",
    next: "Next",
    createDemo: "Create My Demo",
    helpWhatsApp: "Help via WhatsApp",
    demoReady: "Perfect! Your Demo is on the Way",
    demoArriving: "Your demo will arrive in less than 24 hours",
    demoDescription:
      "We have received all your information and our team is already working on creating a personalized demo specifically for your business.",
    sendPersonalizedDemo: "To send you your personalized demo",
    personalizeYourSolution: "To personalize your solution",
    personalizeVirtualAssistant: "Let's personalize your virtual assistant",
    finalDetailsDemo: "The final details for your perfect demo",
    fullNameRequired: "Full Name *",
    businessEmail: "Business Email *",
    phoneWhatsApp: "Phone/WhatsApp *",
    companyRequired: "Company *",
    yourPosition: "Your Position *",
    haveWebsite: "Do you have a website? *",
    selectOption: "Select an option",
    yesHaveWebsite: "Yes, I have a website",
    noWebsite: "I don't have a website",
    websiteURL: "Your Website URL *",
    helpsUnderstand: "Helps us better understand your business and personalize the demo",
    perfectAlso:
      "Perfect! We can also help you create a website with integrated chatbot. We'll include it in your personalized demo.",
    industrySector: "Industry/Sector *",
    selectIndustry: "Select your industry",
    companySize: "Company Size *",
    selectSize: "Select the size",
    justMe: "Just me",
    employees2to10: "2-10 employees",
    employees11to50: "11-50 employees",
    employees51to200: "51-200 employees",
    employees200plus: "200+ employees",
    mainObjectiveBot: "What is your main objective with the bot? *",
    selectObjective: "Select your objective",
    generateMoreLeads: "Generate more leads/sales",
    improveCustomerService: "Improve customer service",
    automateProcesses: "Automate processes",
    reduceOperationalCosts: "Reduce personnel costs",
    attend247: "Attend 24/7",
    qualifyLeadsAutomatically: "Qualify leads automatically",
    consultationsPerDay: "How many consultations do you receive approximately per day? *",
    selectVolume: "Select the volume",
    consultations1to10: "1-10 consultations",
    consultations11to50: "11-50 consultations",
    consultations51to100: "51-100 consultations",
    consultations100plus: "100+ consultations",
    notSure: "Not sure",
    whatTypeBot: "What type of bot do you need? *",
    salesBot: "Sales Bot",
    supportBot: "Support Bot",
    mixedBot: "Mixed",
    customBot: "Custom",
    generateLeadsClose: "Generate leads and close sales",
    handleConsultationsProblems: "Handle consultations and problems",
    salesSupportCombined: "Sales + Support combined",
    specificFunctions: "Specific functions",
    whatPlatforms: "On which platforms do you want the bot? * (You can select several)",
    monthlyBudget: "Estimated Monthly Budget *",
    selectBudget: "Select your budget",
    budget300to800: "$300 - $800 USD",
    budget800to1500: "$800 - $1,500 USD",
    budget1500to3000: "$1,500 - $3,000 USD",
    budget3000plus: "$3,000+ USD",
    needCustomQuote: "I need a custom quote",
    howUrgent: "How urgent is it to implement this? *",
    selectUrgency: "Select urgency",
    thisWeek: "This week",
    thisMonth: "This month",
    in2to3Months: "In 2-3 months",
    justExploring: "Just exploring",
    alreadyHaveBot: "Do you already have a bot or chatbot? *",
    noFirstBot: "No, it's my first bot",
    yesButNotWorking: "Yes, but it doesn't work well",
    yesButWantBetter: "Yes, but I want a better one",
    haveSeveral: "I have several",
    botTonePersonality: "Bot Tone/Personality *",
    selectTone: "Select the tone",
    professionalFormal: "Professional and formal",
    friendlyClose: "Friendly and close",
    funCasual: "Fun and casual",
    expertTechnical: "Expert and technical",
    customized: "Customized",
    biggestProblem: "What is your biggest current problem with customer service?",
    problemExample: "Ex: We can't attend outside hours, we lose many leads, very slow responses...",
    specialFeatures: "Special features that interest you (Optional)",
    crmIntegration: "CRM Integration",
    automaticPayments: "Automatic payments",
    appointmentsReservations: "Appointments/Reservations",
    productCatalog: "Product catalog",
    orderTracking: "Order tracking",
    satisfactionSurveys: "Satisfaction surveys",
    multipleLanguagesFeature: "Multiple languages",
    advancedAnalyticsFeature: "Advanced analytics",
    expectedROI: "What ROI/result do you expect to obtain? *",
    selectExpectation: "Select your expectation",
    moreLeadsSales: "More leads/sales",
    reducePersonnelCosts: "Reduce personnel costs",
    betterCustomerExperience: "Better customer experience",
    attention247: "24/7 attention",
    automateProcessesResult: "Automate processes",
    allAbove: "All of the above",
    doubtsWhileCompleting: "Do you have doubts while completing the form?",
    personalizedDemoReady: "Personalized demo ready",
    specificConfiguration: "Specific configuration",
    readyToImplement: "Ready to implement",
    anyQuestionsWhile: "Any questions in the meantime?",
  },
}

export default function LanguageSwitcher() {
  const [currentLang, setCurrentLang] = useState("es")

  useEffect(() => {
    // Load saved language from localStorage
    const savedLang = localStorage.getItem("language") || "es"
    setCurrentLang(savedLang)
    applyTranslations(savedLang)
  }, [])

  const toggleLanguage = () => {
    const newLang = currentLang === "es" ? "en" : "es"
    setCurrentLang(newLang)
    localStorage.setItem("language", newLang)
    applyTranslations(newLang)
  }

  const applyTranslations = (lang: string) => {
    const langTranslations = translations[lang]

    // Apply translations to elements with data-translate attribute
    document.querySelectorAll("[data-translate]").forEach((element) => {
      const key = element.getAttribute("data-translate")
      if (key && langTranslations[key]) {
        element.textContent = langTranslations[key]
      }
    })

    // Update document language
    document.documentElement.lang = lang
  }

  return (
    <Button
      onClick={toggleLanguage}
      variant="outline"
      size="sm"
      className="border-slate-600 text-gray-300 hover:text-cyan-400 hover:border-cyan-400 transition-all duration-300 bg-transparent"
    >
      <Globe className="w-4 h-4 mr-2" />
      {currentLang === "es" ? "EN" : "ES"}
    </Button>
  )
}
